
### Create user
POST {{base_url}}/users
Content-Type: application/json
Accept: application/json

{
  "username": "{{user}}",
  "password": "{{password}}",
  "email": "{{user}}@email.com"
}

### Invalid create user body
POST {{base_url}}/users/me
Content-Type: application/json
Accept: application/json

{
  "username": "{{user}}",
  "password": "{{password}}"
}

### Login
POST {{base_url}}/auth/tokens
Content-Type: application/json
Accept: application/json

{
  "username": "{{user}}",
  "password": "{{password}}"
}

> {%
 client.global.set("auth_token", response.body.token);
%}

### Add wallet
POST {{base_url}}/users/me/wallets
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

[
  "0x4d864b0ddec2a861506c8baa676e2d99a4c30a84",
  "0x461cde402c6b945036df1b49f2703fca22b23d7b",
  "0x800c0ee9e3f8ea44b6f240ebd68bba5745ce9013"
]

### Delete wallet
DELETE {{base_url}}/users/me/wallets
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

[
  "0x800c0ee9e3f8ea44b6f240ebd68bba5745ce9013"
]

### Get wallets
GET {{base_url}}/users/me/wallets
Accept: application/json
Authorization: Bearer {{auth_token}}


### Get prizes
GET {{base_url}}/users/me/prizes
Accept: application/json
Authorization: Bearer {{auth_token}}

### Admin ###

### Clear cache
DELETE {{base_url}}/admin/cache
Accept: application/json
X-Api-Key: {{admin_api_key}}

### Create admin account
POST {{base_url}}/admin/users
Content-Type: application/json
Accept: application/json
X-Api-Key: {{admin_api_key}}

{
  "username": "{{admin_user}}",
  "password": "{{admin_password}}",
  "email": "{{admin_user}}@email.com"
}

### Admin login
POST {{base_url}}/auth/tokens
Content-Type: application/json
Accept: application/json

{
  "username": "{{admin_user}}",
  "password": "{{admin_password}}"
}

> {%
 client.global.set("auth_admin_token", response.body.token);
%}

### Clear cache with admin token
DELETE {{base_url}}/admin/cache
Accept: application/json
Authorization: Bearer {{auth_admin_token}}