{
 "title": "Pooly Observability Dashboard",
 "tags": [
  "pooly",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,15m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Api Calls Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "c60a5767", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name = \"api\" && span.http.response.status_code != 0 }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Api Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"api\"}"
    }
   ]
  },
  {
   "title": "Api Performance Profile",
   "type": "flamegraph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "labelSelector": "{service_name=\"api\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "Database Query Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "filters": [
      { "id": "c60a5767", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{span.db.system =~ \"postgresql|mysql\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Worker Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"worker\"}"
    }
   ]
  }
 ]
}