app:
  host: "$KTOR_HOST:0.0.0.0"
  port: "$KTOR_PORT:8080"
  loglevel: "$LOG_LEVEL:debug"
  metrics:
    minFreeMem: 256
    maxLoad: 0.75
  database:
    driver: "$DB_DRIVER:org.h2.Driver"
    host: "$DB_HOST:localhost"
    port: "$DB_PORT:5432"
    name: "$DB_NAME:pooly"
    username: "$DB_USERNAME:user"
    password: "$DB_PASSWORD:password"
  cache:
    type: "$CACHE_TYPE:INMEMORY"
    host: "$CACHE_HOST:localhost"
    port: "$CACHE_PORT:6379"
    defaultTTL: "$CACHE_DEFAULT_TTL:PT2M"
    cleanupInterval: "$CACHE_INMEMORY_CLEANUP_INTERVAL:PT10M"
  security:
    hashing:
      argon2Type: "$HASHING_ARGON2_TYPE:ARGON2id"
      iterations: "$HASHING_ARGON2_ITERATIONS:2"
      memory: "$HASHING_ARGON2_MEMORY:20000"
      parallelism: "$HASHING_ARGON2_PARALLELISM:1"
    jwt:
      secret: "$JWT_SECRET:e0df4b2b82be5c9bb10de9cd1f"
    apikey: "$API_KEY:ecb9e77f-339b-4bb7-85e2-6ddb53e8ea8a"
