app:
  checkInterval: "${CHECK_INTERVAL:-PT1H}"
  database:
    driver: "${DB_DRIVER:-org.h2.Driver}"
    host: "${DB_HOST:-localhost}"
    port: "${DB_PORT:-5432}"
    name: "${DB_NAME:-pooly}"
    username: "${DB_USERNAME:-user}"
    password: "${DB_PASSWORD:-password}"
