app:
  checkInterval: "${CHECK_INTERVAL:-5m}"
  db:
    url: "${DB_URL:-jdbc:h2:mem:test;DB_CLOSE_DELAY=-1}"
    driver: "${DB_DRIVER:-org.h2.Driver}"
    user: "${DB_USERNAME:-user}"
    password: "${DB_PASSWORD:-password}"
